name: Robot Framework Master Pipeline

on:
  push:
    branches: [ "main" ]

permissions:
  contents: write

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v5
      with:
        python-version: '3.11'

    - name: Install Dependencies
      run: |
        python -m pip install --upgrade pip
        pip install robotframework robotframework-browser robotframework-pabot robotframework-requests
        # Installeer XVFB (het virtuele scherm)
        sudo apt-get update
        sudo apt-get install -y xvfb

    - name: Initialize Browser Library
      run: rfbrowser init

    - name: Run All Tests Parallel
      run: |
        xvfb-run pabot --processes 3 \
        --variable HEADLESS:True \
        --variable SLOWMO:0.0s \
        --listener "Browser.NoContext" \
        -d results tests

    - name: Deploy Report to GitHub Pages
      # 'if: always()' zorgt dat het rapport ALTIJD wordt ge√ºpload, ook als tests falen
      if: always()
      uses: peaceiris/actions-gh-pages@v3
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        publish_dir: ./results

        # Om alleen smoke tests te draaien:
      run: xvfb-run pabot --include smoke -d results tests  