name: Robot Framework Tests

on: [push]

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install System Dependencies for Browser
        run: npx playwright install-deps

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install robotframework robotframework-browser robotframework-requests
          rfbrowser init

      - name: Run Robot Framework Tests
        # We gebruiken één stap voor de uitvoering
        run: python -m robot -d results -v URL:https://the-internet.herokuapp.com .
        # Hieronder voegen we de cruciale instellingen toe:
        env:
          RW_BROWSER_PAUSE_ON_FAILURE: "False"
          PWDEBUG: 0
        # Zorg dat de workflow doorgaat naar uploaden, ook als een test faalt
        continue-on-error: true

      - name: Upload Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: results/