name: Robot Framework Tests

on: [push] # De tests starten bij elke 'git push'

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      - name: Code ophalen
        uses: actions/checkout@v4

      - name: Python instellen
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Afhankelijkheden installeren
        run: |
          pip install robotframework robotframework-browser
          # De --pnpm vlag en de systeem-dependencies zijn nodig voor Linux runners
          rfbrowser init
          npx playwright install-deps

      - name: Install Browser
        run: rfbrowser init

      - name: Draai de Robot tests
        run: |
          python -m robot -d results -v URL:https://the-internet.herokuapp.com .
        # De punt aan het einde betekent: draai alle .robot bestanden in deze map

      - name: Run Robot Framework Tests
        run: python -m robot .
        continue-on-error: true

      - name: Upload Robot Framework Results
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: robot-results
          path: |
            log.html
            report.html
            browser/screenshot/